### PR TITLE
update to recent versions in travis

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by tarcieri** [comment]
Thanks, although I'm not sure the tests are presently passing anyway...

**Comment by nijikon** [comment]
If we want to support `rbnacl >= 5.0.0` we should drop support for ruby lower than `2.2.6` as stated in the error message `rbnacl-5.0.0 requires ruby version >= 2.2.6, which is incompatible with the`. Are you ok with that?

**Comment by tarcieri** [comment]
Sure

**Comment by nijikon** [comment]
OK, will create a separate PR for that and then update this one.

**Comment by tarcieri** [comment]
Looks good, thanks!

**Pull request merged**
